package simulassandra.client.app;

import java.util.Scanner;

import com.datastax.driver.core.Host;
import com.datastax.driver.core.Metadata;

public class Interactor {
	
	public static void welcome(){
		System.out.println("Simulassandra Client");
	}
	
	public static String getHostAddress(){
		Scanner sc = new Scanner(System.in);
    	System.out.println("Please, tip the host address :");
    	return sc.nextLine();
	}
	
	public static String commandInput(){
		Scanner sc = new Scanner(System.in);
		System.out.print("> ");
		return sc.nextLine();
	}
	
	public static void checkingHost(String h){
		System.out.println("Checking if "+h+" host is reachable.");
	}
	
	public static void displayMetadata(Metadata m){
		System.out.printf("Connected to cluster: %s\n", m.getClusterName());
		for ( Host host : m.getAllHosts() ) {
			System.out.printf("Datacenter: %s; Host: %s; Rack: %s\n",
		    host.getDatacenter(), host.getAddress(), host.getRack());
		}
	}
	
	public static void displayException(Exception e){
		System.out.println("Error > "+e.getMessage());
	}

	public static void end(){
		System.out.println("End");
	}
	
	public static void showCommands(){
		System.out.println("Lists of commands available : ");
		System.out.println("- help : show this list");
		System.out.println("- import <file> : execute cql queries written in the file");
		System.out.println("- keyspace <ks> : switch to keyspace ks");
		System.out.println("- reset : Reset data of the current keyspace");
		System.out.println("- queries <s> : execute queries generated by the seed s on the current keyspace");
	}
}
